project:
  type: website
  output-dir: .

website:
  title: "Research"
  navbar:
    background: primary
    left:
      - icon: house-door
        href: https://shah-in-boots.github.io
      - text: Overview
        href: index.qmd
    right:
      - text: github
        icon: github
        href: https://github.com/shah-in-boots/research
  page-navigation: true
  page-footer: "Copyright (c) 2024, Anish. S. Shah, MD, MS"

bibliography:
  - ../bibliography/publications.bib
  - ../bibliography/cardiology.bib
  - ../bibliography/arrhythmia.bib
  - ../bibliography/computational.bib
  - ../bibliography/epidemiology.bib

format:
  html:
    theme:
      - flatly
      - colors.scss
    highlight: solarized-light
    toc: true
    toc_float: true
  docx:
    reference-doc: template.docx
    notes-after-punctuation: true
  revealjs:
    theme:
      - simple
      - colors.scss
    slide-tone: false
    fig-cap-location: bottom
    fig-align: center
    fig-responsive: true


