project:
  type: website
  output-dir: .

website:
  title: "Research"
  navbar:
    background: primary
    left:
      - icon: house-door
        href: https://asshah4.github.io
      - text: Overview
        href: index.qmd
    right:
      - icon: envelope
        href: mailto:ashah282@uic.edu
      - icon: github
        href: http://github.com/asshah4
      - icon: twitter
        href: https://twitter.com/shah_in_boots
      - icon: linkedin
        href: https://www.linkedin.com/in/anish-shah-326991177/
  page-navigation: true
  page-footer: "Copyright (c) 2022, Anish. S. Shah, MD, MS"

bibliography:
  - ../bibliography/publications.bib
  - ../bibliography/research.bib
  - ../bibliography/cardiology.bib
  - ../bibliography/arrhythmia.bib
  - ../bibliography/computational.bib
  - ../bibliography/epidemiology.bib

format:
  html:
    theme: flatly
    highlight: solarized-light
    css: styles.css
    toc: true
    toc_float: true
  docx:
    reference-doc: template.docx
    notes-after-punctuation: true
  revealjs:
    theme: [simple, styles.scss]
    slide-tone: false
    fig-cap-location: bottom
    fig-align: center
    fig-responsive: true


